name: Emacs org babel tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        python -m pip install --upgrade pip
        pip install pandas tabulate
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      
    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.4

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 15


    - name: Run Tests
      shell: bash
      run: |
        cd tests
        ./run_expect_tests.sh

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: tests/test-results.xml
        report_individual_runs: true
